# Matrix Multiplication in Python

### Without numpy or other modules

Author : Jishnu S G<br>
GitHub : https://github.com/jishnukoliyadan

### <u>Sample</u>

<pre>

A = [[2 , 6 , 8],
     [2 , 9 , 5],
     [5 , 2 , 4]]
B = [[1 , 0 , 5],
     [3 , 2 , 4],
     [4 , 0 , 8]]
     
<b>A * B = [[52 , 12 , 98],
         [49 , 18 , 86],
         [27 ,  4 , 65]]</b>

C = [[6 , 8],
     [4 , 7]]
D = [[3 , 2 , 4 , 6 , 7],
     [2 , 4 , 5 , 2 , 1]]

<b>c* D = [[34 , 44 , 64 , 52 , 50],
        [26 , 36 , 51 , 38 , 35]]</b> 

E = [[4 , 2],
     [5 , 8]]
F = [[5 , 8],
     [4 , 2],
     [7 , 9],
     [8 , 6]]

<b>E * F = Not Possible</b>
</pre>

In [1]:
def matrix_mul(A, B):
    
  lenA = len(A)
  lenB = len(B)
    
  result = 'is Not Possible'

  if lenA == lenB:
    R_columns = len(B[0])
    result = [ [0 for column in range(R_columns)] for row in range(lenA)]
    
    for i in range(len(A)):
      for j in range(R_columns):
        for k in range(len(B)):
            
          result[i][j] += A[i][k] * B[k][j]
        
  return result


A = [[2, 6, 8], [2, 9, 5], [5, 2, 4]]
B = [[1, 0, 5], [3, 2, 4], [4, 0, 8]]

C = [[6, 8], [4, 7]]
D = [[3, 2, 4, 6, 7], [2, 4, 5, 2, 1]]

E = [[4, 2], [5, 8]]
F = [[5, 8], [4, 2], [7, 9], [8, 6]]


print('A * B =', matrix_mul(A, B), '\n')

print('C * D =', matrix_mul(C, D), '\n')

print('E * F', matrix_mul(E, F))

A * B = [[52, 12, 98], [49, 18, 86], [27, 4, 65]] 

C * D = [[34, 44, 64, 52, 50], [26, 36, 51, 38, 35]] 

E * F is Not Possible


## Confirming answers using **Numpy** module

In [2]:
import numpy as np


A = [[2, 6, 8], [2, 9, 5], [5, 2, 4]]
B = [[1, 0, 5], [3, 2, 4], [4, 0, 8]]

C = [[6, 8], [4, 7]]
D = [[3, 2, 4, 6, 7], [2, 4, 5, 2, 1]]

E = [[4, 2], [5, 8]]
F = [[5, 8], [4, 2], [7, 9], [8, 6]]


try:
    print('A * B =', np.matmul(A, B), '\n')
    print('C * D =', np.matmul(C, D), '\n')
    print('E * F =')
    print(np.matmul(E, F))
    
except Exception as e:
    print(e)

A * B = [[52 12 98]
 [49 18 86]
 [27  4 65]] 

C * D = [[34 44 64 52 50]
 [26 36 51 38 35]] 

E * F =
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)
